
-- v01_03_create_table_roles.sql

-- \echo 'Starts v01_03_create_table_roles.sql';

create table roles (
    id integer generated by default as identity,
    authority varchar(20) unique,
    primary key (id)
);

-- \echo 'Ends v01_03_create_table_roles.sql';