
-- v01_02_create_table_products.sql

-- \echo 'Starts v01_02_create_table_products.sql';

create table products (
    amount integer not null check ((amount>=0) and (amount<=100000)),
    created_at date,
    deleted_at date default null,
    id integer generated by default as identity,
    id_owner integer,
    price float4 not null check ((price>=10) and (price<=100000)),
    name varchar(70) not null unique,
    description varchar(256),
    primary key (id)
);

-- \echo 'Ends v01_02_create_table_products.sql';