
-- v01_05_create_table_users_picture.sql

-- \echo 'Starts v01_05_create_table_users_picture.sql';

create table users_picture (
    id integer generated by default as identity,
    id_user integer,
    created_at timestamp(6) not null,
    deleted_at timestamp(6),
    type varchar(32) not null,
    file bytea not null,
    primary key (id)
);

-- \echo 'Ends v01_05_create_table_users_picture.sql';
