
-- v01_04_create_table_users.sql

-- \echo 'Starts v01_04_create_table_users.sql';

create table users (
    id integer generated by default as identity,
    picture_id integer unique,
    created_at timestamp(6),
    deleted_at timestamp(6),
    updated_at timestamp(6),
    username varchar(16) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
);

-- \echo 'Ends v01_04_create_table_users.sql';

