
-- \echo 'Starts v01_01_create_table_product_images';

create table product_images (
    id integer generated by default as identity,
    id_product integer not null,
    created_at timestamp(6) not null,
    deleted_at timestamp(6),
    type varchar(32),
    name varchar(64),
    image bytea not null,
    primary key (id)
);

-- \echo 'Ends v01_01_create_table_product_images';